language: php

php:
  - 5.6
  - 7.0


before_script:
  - npm install -g bower
  - cd sigenes
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - bower install
  - php artisan migrate

script:
  - vendor/bin/phpunit