language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
    allow_failures:
        - php: 7.0

before_script:
  - cd sigenes
  - ls
  - pwd
  - mv .env.example .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - sudo chown -R $USER:$USER /home/travis/build/enesleon
  - sudo chmod -R 755 /home/travis/build/enesleon

script:
  - vendor/bin/phpunit